/**
 * This code was generated by v0 by Vercel.
 * @see https://v0.dev/t/KKhWHcWuFl8
 * Documentation: https://v0.dev/docs#integrating-generated-code-into-your-nextjs-app
 */
interface AppleIconProps extends React.SVGAttributes<SVGSVGElement> {
  className?: string;
}

interface CoffeeIconProps extends React.SVGAttributes<SVGSVGElement> {
  className?: string;
}

interface CupSodaIconProps extends React.SVGAttributes<SVGSVGElement> {
  className?: string;
}

interface PlusIconProps extends React.SVGAttributes<SVGSVGElement> {
  className?: string;
}

export function Menu() {
  return (
    <div className="flex flex-col lg:flex-row lg:space-x-40 text-left">
      <div className="flex flex-col space-y-20">
        <section>
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-2">
              <CupSodaIcon className="h-6 w-6" />
              <h2 className="text-2xl font-bold">Milk Tea</h2>
            </div>
            <div className="flex space-x-4 font-semibold ml-10">
              <span>REGULAR</span>
              <span className="text-right">
                <span className="font-normal italic">4.00</span>
              </span>
              <span>LARGE</span>
              <span className="text-right">
                <span className="font-normal italic">4.75</span>
              </span>
            </div>
          </div>
          <div className="grid grid-cols-3 gap-4 mt-4">
            <div>Almond</div>
            <div>Green Apple</div>
            <div>Pineapple</div>
            <div>Brown Sugar</div>
            <div>Hazelnut</div>
            <div>Strawberry</div>
            <div>Bubblegum</div>
            <div>Honeydew</div>
            <div>Ube Taro</div>
            <div>Chocolate</div>
            <div>Lychee</div>
            <div>Watermelon</div>
            <div>Classic</div>
            <div>Mango</div>
            <div>Pandan</div>
            <div>Coconut</div>
          </div>
        </section>
        <section>
          <div className="flex items-center justify-between ">
            <div className="flex items-center space-x-2">
              <CupSodaIcon className="h-6 w-6" />
              <h2 className="text-2xl font-bold">Premium</h2>
            </div>
            <div className="flex space-x-4 font-semibold">
              <span>REGULAR</span>
              <span className="text-right">
                <span className="font-normal italic">4.90</span>
              </span>
              <span>LARGE</span>
              <span className="text-right">
                <span className="font-normal italic">5.50</span>
              </span>
            </div>
          </div>
          <div className="grid grid-cols-3 gap-4 mt-4">
            <div>Almond</div>
            <div>Green Apple</div>
            <div>Pineapple</div>
            <div>Brown Sugar</div>
            <div>Hazelnut</div>
            <div>Strawberry</div>
            <div>Bubblegum</div>
            <div>Honeydew</div>
            <div>Ube Taro</div>
            <div>Chocolate</div>
            <div>Lychee</div>
            <div>Watermelon</div>
            <div>Classic</div>
            <div>Mango</div>
            <div>Pandan</div>
            <div>Coconut</div>
          </div>
        </section>
        <section>
          <div className="flex items-center justify-between">
            <div className="flex items-center space-x-2">
              <AppleIcon className="h-6 w-6" />
              <h2 className="text-2xl font-bold">Fruit Tea</h2>
            </div>
            <div className="flex space-x-4 font-semibold">
              <span>REGULAR</span>
              <span className="text-right">
                <span className="font-normal italic">3.50</span>
              </span>
              <span>LARGE</span>
              <span className="text-right">
                <span className="font-normal italic">4.00</span>
              </span>
            </div>
          </div>
          <div className="grid grid-cols-2 gap-4 mt-4">
            <div>Lychee</div>
            <div>Mango</div>
            <div>Pineapple</div>
            <div>Passionfruit</div>
            <div>Strawberry</div>
            <div>Watermelon</div>
            <div>Cantaloupe</div>
            <div>Green Apple</div>
            <div>Honeydew</div>
          </div>
        </section>
      </div>
      <div className="flex flex-col space-y-8 lg:w-1/3  ">
        <section>
          <div className="flex items-center space-x-2 mt-10 ">
            <PlusIcon className="h-6 w-6" />
            <h2 className="text-2xl font-bold">Add-ons</h2>
          </div>
          <div className="grid grid-cols-3 gap-4 mt-4">
            <div>
              <h3 className="font-semibold">Nata De Coco:</h3>
              <div>Lychee</div>
              <div>Mango</div>
              <div>Pineapple</div>
            </div>
            <div>
              <h3 className="font-semibold">Popping Boba</h3>
              <div>Lychee</div>
              <div>Mango</div>
              <div>Strawberry</div>
            </div>
            <div>
              <h3 className="font-semibold">Jelly</h3>
              <div>Rainbow Jelly</div>
              <div>Grass Jelly</div>
            </div>
          </div>
        </section>
        <section>
          <div className="flex items-center space-x-2 mt-10">
            <CoffeeIcon className="h-6 w-6" />
            <h2 className="text-2xl font-bold">Bubble-Tea Options</h2>
          </div>
          <div className="grid grid-cols-3 gap-4 mt-4">
            <div>
              <h3 className="font-semibold">Sugar</h3>
              <div>Regular</div>
              <div>Half</div>
              <div>None</div>
            </div>
            <div>
              <h3 className="font-semibold">Ice</h3>
              <div>Regular</div>
              <div>Half</div>
              <div>None</div>
            </div>
            <div>
              <h3 className="font-semibold">Non-Dairy</h3>
              <div>Oat Milk</div>
              <div>Warm</div>
            </div>
          </div>
        </section>
      </div>
    </div>
  );
}

function AppleIcon(props: AppleIconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M12 20.94c1.5 0 2.75 1.06 4 1.06 3 0 6-8 6-12.22A4.91 4.91 0 0 0 17 5c-2.22 0-4 1.44-5 2-1-.56-2.78-2-5-2a4.9 4.9 0 0 0-5 4.78C2 14 5 22 8 22c1.25 0 2.5-1.06 4-1.06Z" />
      <path d="M10 2c1 .5 2 2 2 5" />
    </svg>
  );
}

function CoffeeIcon(props: CoffeeIconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M10 2v2" />
      <path d="M14 2v2" />
      <path d="M16 8a1 1 0 0 1 1 1v8a4 4 0 0 1-4 4H7a4 4 0 0 1-4-4V9a1 1 0 0 1 1-1h14a4 4 0 1 1 0 8h-1" />
      <path d="M6 2v2" />
    </svg>
  );
}

function CupSodaIcon(props: CupSodaIconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="m6 8 1.75 12.28a2 2 0 0 0 2 1.72h4.54a2 2 0 0 0 2-1.72L18 8" />
      <path d="M5 8h14" />
      <path d="M7 15a6.47 6.47 0 0 1 5 0 6.47 6.47 0 0 0 5 0" />
      <path d="m12 8 1-6h2" />
    </svg>
  );
}

function PlusIcon(props: PlusIconProps) {
  return (
    <svg
      {...props}
      xmlns="http://www.w3.org/2000/svg"
      width="24"
      height="24"
      viewBox="0 0 24 24"
      fill="none"
      stroke="currentColor"
      strokeWidth="2"
      strokeLinecap="round"
      strokeLinejoin="round"
    >
      <path d="M5 12h14" />
      <path d="M12 5v14" />
    </svg>
  );
}
